name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        pip install PyYAML
    - name: Install Conan
      uses: turtlebrowser/get-conan@v1.2
      with:
        version: "1.6.0"
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: ' --from-ref origin/master --to-ref HEAD'
